version: "3"
services:
  file-service:
    image: file-service
    build:
      context: ./file-service
      dockerfile: Dockerfile
    container_name: file-serivce
    environment:
      - PORT=81
    restart: "no"
    networks:
      - internal-communication
  video-streaming:
    image: video-streaming
    build:
      context: ./video-streaming
      dockerfile: Dockerfile
    container_name: video-streaming
    ports:
      - "4000:80"
    environment:
      - PORT=80
      - FILE_SERVICE_HOST=file-service
      - FILE_SERVICE_PORT=81
    restart: "no"
    networks:
      - internal-communication
networks:
  internal-communication: {}

